services:
  osmocom-bb-freertos: &base
    build:
      context: .
      dockerfile: Dockerfile
      args:
        FREERTOS_KERNEL_REF: ${FREERTOS_KERNEL_REF:-V11.0.1}
        FREERTOS_TCP_REF: ${FREERTOS_TCP_REF:-V4.1.0}
        LIBOSMOCORE_REF: ${LIBOSMOCORE_REF:-master}
    image: osmocom-bb:freertos
    working_dir: /workspace
    volumes:
      - ./:/workspace:delegated
      - freertos-build:/opt/freertos-build
      - libosmocore-cache:/workspace/deps/libosmocore
    tty: true
    stdin_open: true
    environment:
      FREERTOS_KERNEL_REF: ${FREERTOS_KERNEL_REF:-V11.0.1}
      FREERTOS_TCP_REF: ${FREERTOS_TCP_REF:-V4.1.0}
      LIBOSMOCORE_REF: ${LIBOSMOCORE_REF:-master}
      TARGET_FREERTOS: 1
      TARGET_POSIX: 1
    command: ["/bin/bash", "-lc", "echo 'Use: docker compose run shell' or 'docker compose run build'"]

  shell:
    <<: *base
    entrypoint: ["/bin/bash", "-lc"]
    command: ["source scripts/freertos_env.sh && exec bash"]

  build:
    <<: *base
    entrypoint: ["/bin/bash", "-lc"]
    command: ["source scripts/freertos_env.sh && mkdir -p build-freertos build-posix && echo 'Build environment ready. Run cmake or make commands as needed.'"]

  dev:
    <<: *base
    entrypoint: ["/bin/bash", "-lc"]
    command: ["source scripts/freertos_env.sh && exec bash"]
    volumes:
      - ./:/workspace:delegated
      - freertos-build:/opt/freertos-build
      - libosmocore-cache:/workspace/deps/libosmocore
      - dev-home:/root

  test:
    <<: *base
    entrypoint: ["/bin/bash", "-lc"]
    command: ["source scripts/freertos_env.sh && echo 'Running tests...' && echo 'Tests would run here.'"]

volumes:
  freertos-build:
    driver: local
  libosmocore-cache:
    driver: local  
  dev-home:
    driver: local

networks:
  default:
    name: osmocom-bb-freertos

name: osmocom-bb-freertos